### ISSUE TITLE
找不到文件

### ISSUE THREAD

**Issue by UPman24** [maioria/chatgpt-talkieai#1]
sh: ../../../gitee/scio-talkie/scio-talkie-uniapp/node_modules/.bin/uni: No such file or directory

**Comment by maioria** [comment]
运行前需要先安装npm依赖，执行npm install

**Comment by UPman24** [comment]
> 运行前需要先安装npm依赖，执行npm install

1.npm install 之后运行了 npm run dev:h5

```
> uni-preset-vue@0.0.0 dev:h5
> ../../../gitee/scio-talkie/scio-talkie-uniapp/node_modules/.bin/uni

sh: ../../../gitee/scio-talkie/scio-talkie-uniapp/node_modules/.bin/uni: No such file or directory
```

**Comment by maioria** [comment]
package.json里面配置的路径不正确，问题已经修复了，可以更新试试

**Comment by maioria** [comment]
问题已修复
